version: "3.8"

services:
  next-app:
    container_name: next-app
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start"]
