version: "3.3"
services:
  strapi:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "1337:1337" # Ensure the correct port mapping
    environment:
      HOST: "0.0.0.0"
      PORT: "1337"
      URL: "http://147.93.97.188:1337"
    command: sh -c "npm install && npm start"
