apiVersion: apps/v1
kind: Deployment
metadata:
  name: decor-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: decordukaan/decordukaan-strapi-app:latest
          ports:
            - containerPort: 1337
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: database_url
            - name: CLOUDINARY_NAME
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: cloudinary_name
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: cloudinary_key
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: cloudinary_secret
            - name: RAZORPAY_KEY
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: razorpay_key
            - name: RAZORPAY_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: razorpay_secret